image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      git config --global user.name $GIT_AUTHOR_NAME
      git config --global user.email $GIT_COMMITTER_EMAIL
      gh repo fork --remote
      go get github.com/cpuguy83/go-md2man
      git submodule update --init
      make tag
